name: Apply

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      Environment:
        description: "Which environment to deploy e.g. dev, uat"
        required: true
        type: choice
        options: 
          - dev
          - uat

jobs:

  Terraform_action_build:

    name: Terraform_action_build
    runs-on: ubuntu-latest

    steps:
      - name: checkout_actions
        uses: actions/checkout@v4

      - name: set up terraform hashicorp 
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Corrected variable name
          aws-region: ${{ secrets.AWS_REGION }}

      # Runs a single command using the runner's shell
      - name: Terraform init
        run: | 
          cd module
          terraform init
          # -backend-config="bucket=parasec2tfstatefile"
          # -backend-config="key=terraform.tfstate"

      - name: plan
        run: |
          cd module
          terraform plan

      - name: apply
        run: |
          cd module 
          terraform apply -auto-approve
